name: Generate Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  changelog:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Important for getting all commits
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli
          
      - name: Generate Changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: Update CHANGELOG.md"
          git push 